In [1]:
import torch
a = torch.ones(3)
print(a)
print(a[0])
print(float(a[1]))
a[2] = 2.0
print(a)

tensor([1., 1., 1.])
tensor(1.)
1.0
tensor([1., 1., 2.])


In [2]:
points = torch.zeros(6)
print(points)
points[0] = 4.0
points[1] = 1.0
points[2] = 5.0
points[3] = 3.0
points[4] = 2.0
points[5] = 1.0
print(points)

tensor([0., 0., 0., 0., 0., 0.])
tensor([4., 1., 5., 3., 2., 1.])


In [3]:
points = torch.tensor([4.0, 1.0, 5.0, 3.0, 2.0, 1.0])
print(points)

tensor([4., 1., 5., 3., 2., 1.])


In [4]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
print(points)
print(points.shape)
print(points[0]) # 0番目の２次元座標を取得できる
print(points[2, 1]) # 2番目のY座標を取得できる

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])
torch.Size([3, 2])
tensor([4., 1.])
tensor(1.)


In [5]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
print(points[1:]) # 行1位校を指定、暗に列も全部指定
print(points[1: , :]) # 行1以降を指定、明に列も全部指定
print(points[1: , 0]) # 行1以降で列0をすべて指定
print(points[None]) # 新たな次元を追加

tensor([[5., 3.],
        [2., 1.]])
tensor([[5., 3.],
        [2., 1.]])
tensor([5., 2.])
tensor([[[4., 1.],
         [5., 3.],
         [2., 1.]]])


In [6]:
weights_names = torch.tensor([0.2126, 0.7152, 0.0722], names=['channels'])
print(weights_names)

tensor([0.2126, 0.7152, 0.0722], names=('channels',))


/tmp/ipykernel_4646/1677095449.py:1: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at ../c10/core/TensorImpl.h:1928.)
  weights_names = torch.tensor([0.2126, 0.7152, 0.0722], names=['channels'])


In [7]:
# ちょいよくわからん
img_t = torch.randn(3, 5, 5)
weights = torch.tensor([0.2126, 0.7152, 0.0722])
batch_t = torch.randn(2, 3, 5, 5)

img_named = img_t.refine_names(..., 'channels', 'row', 'columns')
batch_named = batch_t.refine_names(..., 'channels', 'row', 'columns')
print("img_named: ", img_named.shape, img_named.names)
print("batch_named: ", batch_named.shape, batch_named.names)

img_named:  torch.Size([3, 5, 5]) ('channels', 'row', 'columns')
batch_named:  torch.Size([2, 3, 5, 5]) (None, 'channels', 'row', 'columns')


In [8]:
print('weights_names:', weights_names.shape, weights_names.name)

weights_aligned = weights_names.align_as(img_named)
print('weights_aligned:', weights_aligned.shape, weights_aligned.names)
print(weights_aligned)

weights_names: torch.Size([3]) None
weights_aligned: torch.Size([3, 1, 1]) ('channels', 'row', 'columns')
tensor([[[0.2126]],

        [[0.7152]],

        [[0.0722]]], names=('channels', 'row', 'columns'))


In [9]:
double_points = torch.ones(10, 2, dtype=torch.double)
short_points = torch.tensor([[1, 2], [3, 4]], dtype=torch.short)

print(double_points)
print(short_points)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]], dtype=torch.float64)
tensor([[1, 2],
        [3, 4]], dtype=torch.int16)


In [10]:
print('double_points: ', double_points.dtype)
print('short_points: ', short_points.dtype)

double_points:  torch.float64
short_points:  torch.int16


In [11]:
double_points = torch.zeros(10, 2).double()
short_points = torch.ones(10, 2).short()
print('double_points: ', double_points.dtype)
print('short_points: ', short_points.dtype)

uint_points = torch.zeros(2, 2).to(torch.uint8)
bool_points = torch.zeros(1, 2).to(torch.bool)
print('uint_points: ', uint_points.dtype)
print('bool_points: ', bool_points.dtype)

double_points:  torch.float64
short_points:  torch.int16
uint_points:  torch.uint8
bool_points:  torch.bool


In [12]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
print(points.storage())

points_storage = points.storage()
print(points_storage[0])
print(points.storage()[1])

 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]
4.0
1.0


/tmp/ipykernel_4646/372007168.py:2: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  print(points.storage())


In [13]:
points_storage[0] = 2.0
print(points_storage)
print(points)

 2.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]
tensor([[2., 1.],
        [5., 3.],
        [2., 1.]])


In [14]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[1]
print(second_point)

print("points_shape: ", second_point.shape)
print("second_point_shape: ", second_point.shape)

print("points_stride: ", points.stride())
print("second_point_stride: ", second_point.stride())

print("points_offset: ", points.storage_offset())
print("second_point_offset: ", second_point.storage_offset())

print("points_storage: \n", points.storage())
print("second_point_storage:\n", second_point.storage())

tensor([5., 3.])
points_shape:  torch.Size([2])
second_point_shape:  torch.Size([2])
points_stride:  (2, 1)
second_point_stride:  (1,)
points_offset:  0
second_point_offset:  2
points_storage: 
  4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]
second_point_storage:
  4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]


In [15]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
print("points: \n", points)
second_point = points[1]

print("second_point: \n", second_point)
second_point[0] = 10.0

print("modified_second_point: \n", second_point)
print("confirm_points: \n", points)

points: 
 tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])
second_point: 
 tensor([5., 3.])
modified_second_point: 
 tensor([10.,  3.])
confirm_points: 
 tensor([[ 4.,  1.],
        [10.,  3.],
        [ 2.,  1.]])


In [16]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
secod_point = points[1].clone()
second_point[0] = 10.0
print("confirm_points: \n", points)
print("points_storage: \n", points.storage())
print("second_point_storage: \n", second_point.storage())

confirm_points: 
 tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])
points_storage: 
  4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]
second_point_storage: 
 4.0
 1.0
 10.0
 3.0
 2.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]


In [17]:
points_gpu = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]], device="cuda")

In [18]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points_gpu = points.to(device="cuda")

In [19]:
points = 2 * points # CPU上で計算
points_gpu = 2 * points.to(device="cuda") # GPU上で計算
points_gpu = points_gpu + 4
points_cpu = points_gpu.to(device="cpu")
print("points_cpu: \n", points_cpu)

points_cpu: 
 tensor([[20.,  8.],
        [24., 16.],
        [12.,  8.]])


In [20]:
import imageio

img_arr = imageio.imread("cat.jpeg")
print(img_arr.shape)

(187, 270, 3)


/tmp/ipykernel_4646/892193373.py:3: DeprecationWarning: Starting with ImageIO v3 the behavior of this function will switch to that of iio.v3.imread. To keep the current behavior (and make this warning disappear) use `import imageio.v2 as imageio` or call `imageio.v2.imread` directly.
  img_arr = imageio.imread("cat.jpeg")


In [21]:
img = torch.from_numpy(img_arr)
out = img.permute(2, 0, 1)
print(out.shape)

torch.Size([3, 187, 270])


In [22]:
batch_size = 3
batch = torch.zeros(batch_size, 3, 256, 256, dtype=torch.uint8)
print(batch.shape)

torch.Size([3, 3, 256, 256])


In [23]:
import os
from torchvision.io import read_image
import torchvision.transforms.functional as F

data_dir = "/home/ee/ee33045l/EE4_2F-pytorch"
filenames = [name for name in os.listdir(data_dir)
            if os.path.splitext(name)[-1] == ".jpeg"]
for i, filename in enumerate(filenames):
    image = read_image(os.path.join(data_dir, filename))
    image_re = F.resize(img=image, size=(256, 256))
    batch[i] = image_re

In [24]:
batch = batch.float()
n_channels =  batch.shape[1]
for c in range(n_channels):
    mean = torch.mean(batch[:, c])
    std = torch.std(batch[:, c])
    batch[:, c] = (batch[:, c] - mean) / std

In [25]:
# 4.1 (1)
import torch

# list(range(9))からテンソルを作成
a = torch.tensor(list(range(9)))
print(a)

# サイズ
print("サイズ: ", a.shape)

# オフセット
print("オフセット: ", a.storage_offset())

# ストライドを確認
print("ストライド: ", a.stride())

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])
サイズ:  torch.Size([9])
オフセット:  0
ストライド:  (1,)


In [26]:
# 4.1 (2)
b = a.view(3, 3)
print(b)
print("viewにはテンソルのサイズを変更する働きがある")

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
viewにはテンソルのサイズを変更する働きがある


In [27]:
# 4.1 (3)
print(a, b)

print("aのポインタ: ", a.data_ptr())
print("bのポインタ: ", b.data_ptr())

if a.data_ptr() ==  b.data_ptr():
    print("aとbは同じストレージを利用している！")
else:
    print("aとbは違うストレージを使用している!")

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8]) tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
aのポインタ:  94694598468864
bのポインタ:  94694598468864
aとbは同じストレージを利用している！


In [28]:
# 4.1 (4)
c = b[1:, 1:]
print(c)
print("サイズ: ", c.shape)
print("オフセット: ", c.storage_offset())
print("ストライド: ", c.stride())

tensor([[4, 5],
        [7, 8]])
サイズ:  torch.Size([2, 2])
オフセット:  4
ストライド:  (3, 1)


In [29]:
# 4.2 (1), (2), (3)
import imageio

data_dir = "/home/ee/ee33045l/EE4_2F-pytorch/4-2/redrose/jpeg"

red_img = imageio.imread("/home/ee/ee33045l/EE4_2F-pytorch/4-2/redrose.jpeg")
blue_img = imageio.imread("/home/ee/ee33045l/EE4_2F-pytorch/4-2/bluerose.jpeg")
green_img = imageio.imread("/home/ee/ee33045l/EE4_2F-pytorch/4-2/greenrose.jpeg")

print("赤色明るさ:", red_img.mean())
print("青色明るさ:", blue_img.mean())
print("緑色明るさ:", green_img.mean())

赤色明るさ: 42.967140255009106
青色明るさ: 48.183069333333336
緑色明るさ: 38.95169184414727


/tmp/ipykernel_4646/2522578713.py:6: DeprecationWarning: Starting with ImageIO v3 the behavior of this function will switch to that of iio.v3.imread. To keep the current behavior (and make this warning disappear) use `import imageio.v2 as imageio` or call `imageio.v2.imread` directly.
  red_img = imageio.imread("/home/ee/ee33045l/EE4_2F-pytorch/4-2/redrose.jpeg")
/tmp/ipykernel_4646/2522578713.py:7: DeprecationWarning: Starting with ImageIO v3 the behavior of this function will switch to that of iio.v3.imread. To keep the current behavior (and make this warning disappear) use `import imageio.v2 as imageio` or call `imageio.v2.imread` directly.
  blue_img = imageio.imread("/home/ee/ee33045l/EE4_2F-pytorch/4-2/bluerose.jpeg")
/tmp/ipykernel_4646/2522578713.py:8: DeprecationWarning: Starting with ImageIO v3 the behavior of this function will switch to that of iio.v3.imread. To keep the current behavior (and make this warning disappear) use `import imageio.v2 as imageio` or call `imageio.v

In [32]:
import imageio
import torch

red_img = imageio.imread("./4-2/redrose.jpeg")
blue_img = imageio.imread("./4-2/bluerose.jpeg")
green_img = imageio.imread("./4-2/greenrose.jpeg")

red_tensor = torch.tensor(red_img, dtype=torch.float32)
blue_tensor = torch.tensor(blue_img, dtype=torch.float32)
green_tensor = torch.tensor(green_img, dtype=torch.float32)

print(" 赤色明るさ : ", red_tensor.mean())
print(" 青色明るさ : ", blue_tensor.mean())
print(" 緑色明るさ : ", green_tensor.mean())

 赤色明るさ :  tensor(42.9671)
 青色明るさ :  tensor(48.1831)
 緑色明るさ :  tensor(38.9517)


/var/folders/7c/s01vmy5n6s13cj9wyd5ggsgm0000gn/T/ipykernel_35428/686392741.py:4: DeprecationWarning: Starting with ImageIO v3 the behavior of this function will switch to that of iio.v3.imread. To keep the current behavior (and make this warning disappear) use `import imageio.v2 as imageio` or call `imageio.v2.imread` directly.
  red_img = imageio.imread("./4-2/redrose.jpeg")
/var/folders/7c/s01vmy5n6s13cj9wyd5ggsgm0000gn/T/ipykernel_35428/686392741.py:5: DeprecationWarning: Starting with ImageIO v3 the behavior of this function will switch to that of iio.v3.imread. To keep the current behavior (and make this warning disappear) use `import imageio.v2 as imageio` or call `imageio.v2.imread` directly.
  blue_img = imageio.imread("./4-2/bluerose.jpeg")
/var/folders/7c/s01vmy5n6s13cj9wyd5ggsgm0000gn/T/ipykernel_35428/686392741.py:6: DeprecationWarning: Starting with ImageIO v3 the behavior of this function will switch to that of iio.v3.imread. To keep the current behavior (and make this wa

In [33]:
import torch

red_image_mean = [red_tensor[:, :, 0].mean(), red_tensor[:, :, 1].mean(), red_tensor[:, :, 2].mean()]
blue_image_mean = [blue_tensor[:, :, 0].mean(), blue_tensor[:, :, 1].mean(), blue_tensor[:, :, 2].mean()]
green_image_mean = [green_tensor[:, :, 0].mean(), green_tensor[:, :, 1].mean(), green_tensor[:, :, 2].mean()]

print("[R, G, B]の順で出力される。")
print("赤の画像")
print(red_image_mean)
print("-----")

print("青の画像")
print(blue_image_mean)
print("-----")

print("緑の画像")
print(green_image_mean)

[R, G, B]の順で出力される。
赤の画像
[tensor(71.5677), tensor(21.9460), tensor(35.3877)]
-----
青の画像
[tensor(39.5279), tensor(33.9923), tensor(71.0290)]
-----
緑の画像
[tensor(22.2641), tensor(55.6354), tensor(38.9556)]


In [30]:
# 4.2
import torch

red_image_mean = [red_img[:, :, 0].mean(), red_img[:, :, 1].mean(), red_img[:, :, 2].mean()]
blue_image_mean = [blue_img[:, :, 0].mean(), blue_img[:, :, 1].mean(), blue_img[:, :, 2].mean()]
green_image_mean = [green_img[:, :, 0].mean(), green_img[:, :, 1].mean(), green_img[:, :, 2].mean()]

print("[R, G, B]の順で出力される。")
print("赤の画像")
print(red_image_mean)
print("-----")

print("青の画像")
print(blue_image_mean)
print("-----")

print("緑の画像")
print(green_image_mean)

[R, G, B]の順で出力される。
赤の画像
[71.56767014406358, 21.946030799801292, 35.38771982116244]
-----
青の画像
[39.527888, 33.992276, 71.029044]
-----
緑の画像
[22.264110946012877, 55.63538261515602, 38.955581971272906]
